name: CI

on:
    push:
        branches:
            - master
            - develop

jobs: 
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}
            
            - name: Install dependencies
              run: |
                npm install
            # - name: Run tests
            #   run: |
            #     npm test
            #   env:
            #     CI: true
            - name: Git config
              run: |
                git config --global user.email "eliemugenzi@gmail.com"
                git config --global user.name "eliemugenzi"
            - name: Deploy
              run: |
                npm run deploy

    